# Generated by Django 5.1.2 on 2024-10-22 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etiquetas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Etiquetas que se le puede agregar a una tarea",
                "unique_together": {("autor", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_vencimiento", models.DateTimeField(blank=True)),
                (
                    "progreso",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("c", "Completado"),
                            ("e", "En proceso"),
                            ("n", "No iniciado"),
                        ],
                        default="n",
                        help_text="Estatus de la entrega de la tarea",
                        max_length=1,
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("etiquetas", models.ManyToManyField(to="organizador.etiqueta")),
            ],
        ),
    ]
