# Generated by Django 5.1.2 on 2024-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarea",
            name="etiquetas",
            field=models.ManyToManyField(blank=True, to="organizador.etiqueta"),
        ),
    ]
